server:
  port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/helpdeskmobile
    username: helpdeskmobile
    password: helpdeskmobile
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/liquibase/liquibase-changelog.yaml
security:
  jwt:
    secret: "nbFvTC0zpL6hypeLYVNcSQquqo1OwuHI8Qtla9nXkhCB9AhDIlFReHS1Q5CSsWvuZG0gX8lsKai5KQMxveT2zQrWhGfdd7mAqnonqnQGpKpVftjpSJrVjLbnbZ7I87"
    expiration: 86400000 #24 hours in milliseconds
  admin:
    role: "ADMIN"
    path: "/admin/**"
  public:
    path: "/public/**"