version: '3.1'

services:

  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: helpdeskmobile
      POSTGRES_PASSWORD: helpdeskmobile
    volumes:
      - $HOME/docker/volumes/helpdeskmobile/postgres/data:/var/lib/postgresql/data